dbmusic/dbmusic/Models/Artists.cs
using System;
using System.Collections.Generic;

namespace dbmusic.Models
{
    public partial class Artists
    {
        public int ArtistId { get; set; }
        public string ArtistName { get; set; }
        public string AlbumName { get; set; }
        public string ImageUrl { get; set; }
        public DateTime ReleaseDate { get; set; }
        public decimal Price { get; set; }
        public string SampleUrl { get; set; }
    }
}

dbmusic/dbmusic/Models/ErrorViewModel.cs
using System;

namespace dbmusic.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

dbmusic/dbmusic/Models/dbmusicContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace dbmusic.Models
{
    public partial class dbmusicContext : DbContext
    {
        public dbmusicContext()
        {
        }

        public dbmusicContext(DbContextOptions<dbmusicContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Artists> Artists { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

                optionsBuilder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Artists>(entity =>
            {
                entity.HasKey(e => e.ArtistId);

                entity.Property(e => e.ArtistId).HasColumnName("ArtistID");

                entity.Property(e => e.AlbumName)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.ArtistName)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.ImageUrl)
                    .HasColumnName("ImageURL")
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.Price).HasColumnType("numeric(10, 2)");

                entity.Property(e => e.ReleaseDate).HasColumnType("date");

                entity.Property(e => e.SampleUrl)
                    .HasColumnName("SampleURL")
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

dbmusic/dbmusic/Controllers/APIArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using dbmusic.Models;

namespace dbmusic.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class APIArtistsController : ControllerBase
    {
        private readonly dbmusicContext _context;

        public APIArtistsController(dbmusicContext context)
        {
            _context = context;
        }

        // GET: api/APIArtists
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Artists>>> GetArtists()
        {
            return await _context.Artists.ToListAsync();
        }

        // GET: api/APIArtists/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Artists>> GetArtists(int id)
        {
            var artists = await _context.Artists.FindAsync(id);

            if (artists == null)
            {
                return NotFound();
            }

            return artists;
        }

        // PUT: api/APIArtists/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutArtists(int id, Artists artists)
        {
            if (id != artists.ArtistId)
            {
                return BadRequest();
            }

            _context.Entry(artists).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ArtistsExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/APIArtists
        [HttpPost]
        public async Task<ActionResult<Artists>> PostArtists(Artists artists)
        {
            _context.Artists.Add(artists);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetArtists", new { id = artists.ArtistId }, artists);
        }

        // DELETE: api/APIArtists/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Artists>> DeleteArtists(int id)
        {
            var artists = await _context.Artists.FindAsync(id);
            if (artists == null)
            {
                return NotFound();
            }

            _context.Artists.Remove(artists);
            await _context.SaveChangesAsync();

            return artists;
        }

        private bool ArtistsExists(int id)
        {
            return _context.Artists.Any(e => e.ArtistId == id);
        }
    }
}

dbmusic/dbmusic/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace dbmusic.Controllers
{
    public class ArtistsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

dbmusic/dbmusic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using dbmusic.Models;

namespace dbmusic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

dbmusic/dbmusic/Views/Artists/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@Html.Hidden("hf")
@section Scripts {
    <script src="~/js/Artists.js"></script>
}

<div class="row">
    <div class="action-button">
        <button class="btn btn-primary btn-lg btn-responsive" onclick="addData()"><i class="oi-input oi-plus"></i> Add New</button>
    </div>
</div>
<br>

<div class="row">
    <table id="tblArtist" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Num.</th>
                <th>Album Name</th>
                <th>Artist Name</th>
                <th>Date Release</th>
                <th>Sample Audio</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>

<div id="modalPreview" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div id="modalDialogPreview" class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitlePreview"></h5>
                <button type="button" class="close" data-dismiss="modal" onclick="stop()">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body" style="color:white">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Artist Name</label>
                    <p>:</p>
                    <div class="col-sm-8">
                        <p id="labelArtistName"></p>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Album Name</label>
                    <p>:</p>
                    <div class="col-sm-8">
                        <p id="labelAlbum"></p>
                    </div>
                </div>
                <img id="labelImg" width="300" height="300" style="margin: 0 auto; display: block;">
                <br>
                <audio id="audio" controls style="margin: 0 auto; display: block;">
                    <source id="source" type="audio/mpeg">
                    Your browser does not support the audio element.
                </audio>
            </div>
        </div>
    </div>
</div>

<div id="modalArtist" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div id="modalDialogArtist" class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitleArtist"></h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="ArtistForm" name="Artist" action="#">
                    <div class="form-input">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Artist Name <font class="f-red">*</font></label>
                            <div class="col-sm-8">
                                <input id="txtArtistName" class="form-control form-control-sm" placeholder="Please fill Artist Name" required="" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Album Name <font class="f-red">*</font></label>
                            <div class="col-sm-8">
                                <input id="txtAlbumName" class="form-control form-control-sm" placeholder="Please fill Album Name" required="" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Image Url</label>
                            <div class="col-sm-8">
                                <input id="txtImageUrl" class="form-control form-control-sm" placeholder="Please fill Image Url" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Release Date <font class="f-red">*</font></label>
                            <div class="col-sm-8">
                                <input id="txtReleaseDate" class="form-control form-control-sm" placeholder="Please fill Release Date" required="" autocomplete="off" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Price <font class="f-red">*</font></label>
                            <div class="col-sm-8">
                                <input id="txtPrice" class="form-control form-control-sm" placeholder="Please fill Price" required="" />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label">Sample Url</label>
                            <div class="col-sm-8">
                                <input id="txtSampleUrl" class="form-control form-control-sm" placeholder="Please fill Sample Url" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-dark btn-sm btn-responsive btnSave" type="submit"><i class="oi-input oi-circle-check"></i> Save</button>
                        <button class="btn btn-danger btn-sm btn-responsive" data-dismiss="modal"><i class="oi-input oi-circle-x"></i> Cancel</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

dbmusic/dbmusic/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dbmusic/dbmusic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dbmusic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/lib/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/select.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/buttons.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/lib/open-iconic/font/css/open-iconic-bootstrap.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dbmusic</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artists" asp-action="Index">Artists</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - dbmusic - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.select.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/lib/jquery-ui-1.12.1.js"></script>
    <script src="~/lib/js.js"></script>

    <script>
        $.rootDir = '@Url.Content("~/")';
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>